# fly.toml app configuration file generated for twoway-v1-bold-sun-6634 on 2025-08-05T23:10:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'twoway-v1-bold-sun-6634'
primary_region = 'lhr'

[build]

[env]
  PORT = '3000'
  NODE_ENV = 'production'
  DATABASE_URL = 'file:/data/sqlite.db'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = 'data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
